name: bloc_tracker
description: A powerful, zero-dependency performance profiler for the bloc library.
version: 1.0.1
homepage: https://github.com/yashmakan/bloc_tracker
repository: https://github.com/yashmakan/bloc_tracker
issue_tracker: https://github.com/yashmakan/bloc_tracker/issues

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.1.0
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
